<script setup lang="ts">
import { computed } from 'vue'
import { X } from 'lucide-vue-next'
import PlatformIcon from '@/components/PlatformIcon.vue'
import type { MediaAsset } from '@/types/business'

const props = defineProps<{
  accountName: string
  title: string
  contentHtml: string
  media: MediaAsset[]
  loading?: boolean
  removingId?: number
}>()

const emit = defineEmits<{
  remove: [item: MediaAsset]
  setCover: [item: MediaAsset]
}>()
const cover = computed(() => props.media.find((item) => item.usageType === 'COVER'))
const bodyImages = computed(() => props.media.filter((item) => item.usageType !== 'COVER'))
</script>

<template>
  <article class="wechat-article" data-testid="wechat-platform-preview">
    <div class="preview-label">
      <PlatformIcon platform="WECHAT_OFFICIAL" size="sm" />手机文章预览
    </div>
    <h2>{{ title || '填写标题后在这里预览' }}</h2>
    <div class="article-meta">
      <span>{{ accountName }}</span
      ><span>刚刚</span><span>模拟预览</span>
    </div>

    <figure v-if="cover" class="wechat-cover">
      <img :src="cover.thumbnailUrl || cover.imageUrl" :alt="cover.altText || '公众号封面'" />
      <button
        type="button"
        :disabled="removingId === cover.id"
        :aria-label="`移除图片：${cover.altText || cover.id}`"
        title="移除封面"
        @click.stop="emit('remove', cover)"
      >
        <X :size="13" />
      </button>
    </figure>

    <div v-if="loading" class="formatting-state">正在同步最终排版…</div>
    <!-- contentHtml is sanitized after being generated by the same backend formatter used on save. -->
    <!-- eslint-disable-next-line vue/no-v-html -->
    <div v-else class="wechat-rich-body" v-html="contentHtml" />
    <div v-if="bodyImages.length" class="wechat-body-images">
      <figure v-for="item in bodyImages" :key="item.id">
        <img :src="item.thumbnailUrl || item.imageUrl" :alt="item.altText || '公众号正文配图'" />
        <div>
          <button type="button" @click="emit('setCover', item)">设为封面</button>
          <button type="button" :disabled="removingId === item.id" @click="emit('remove', item)">
            移除
          </button>
        </div>
      </figure>
    </div>

    <footer><span>阅读原文</span><span>在看 · 写留言</span></footer>
  </article>
</template>

<style scoped>
.wechat-article {
  max-width: 360px;
  margin: 0 auto;
  border: 1px solid #e5e7eb;
  border-radius: 12px;
  background: #fff;
  padding: 17px 17px 13px;
  box-shadow: 0 8px 24px rgba(16, 24, 40, 0.06);
}
.preview-label {
  display: flex;
  align-items: center;
  gap: 6px;
  margin-bottom: 15px;
  color: #667085;
  font-size: 10px;
}
h2 {
  margin: 0;
  color: #171717;
  font-size: 20px;
  font-weight: 650;
  line-height: 1.4;
}
.article-meta {
  display: flex;
  gap: 8px;
  margin: 8px 0 16px;
  color: #9aa0a6;
  font-size: 10px;
}
.article-meta span:first-child {
  color: #576b95;
}
.wechat-cover {
  position: relative;
  overflow: hidden;
  margin: 0 0 17px;
  border-radius: 6px;
  background: #f2f4f7;
}
.wechat-cover img {
  display: block;
  width: 100%;
  aspect-ratio: 2.35 / 1;
  object-fit: cover;
}
.wechat-cover button {
  position: absolute;
  top: 6px;
  right: 6px;
  display: grid;
  width: 25px;
  height: 25px;
  place-items: center;
  border: 1px solid rgba(255, 255, 255, 0.72);
  border-radius: 50%;
  background: rgba(18, 24, 38, 0.72);
  color: #fff;
}
.wechat-rich-body {
  max-height: 440px;
  overflow: auto;
}
.wechat-body-images {
  display: grid;
  gap: 10px;
  margin-top: 15px;
}
.wechat-body-images figure {
  position: relative;
  overflow: hidden;
  margin: 0;
  border-radius: 6px;
  background: #f2f4f7;
}
.wechat-body-images img {
  display: block;
  width: 100%;
  max-height: 240px;
  object-fit: cover;
}
.wechat-body-images figure > div {
  position: absolute;
  right: 7px;
  bottom: 7px;
  display: flex;
  gap: 5px;
}
.wechat-body-images figure button {
  border-radius: 999px;
  background: rgba(18, 24, 38, 0.76);
  padding: 4px 8px;
  color: #fff;
  font-size: 9px;
}
.formatting-state {
  display: grid;
  height: 180px;
  place-items: center;
  color: #98a2b3;
  font-size: 11px;
}
footer {
  display: flex;
  justify-content: space-between;
  margin-top: 18px;
  border-top: 1px solid #f0f1f3;
  padding-top: 11px;
  color: #8c8c8c;
  font-size: 10px;
}
footer span:first-child {
  color: #576b95;
}
</style>
