"""complete business modules

Revision ID: d7bc40428afb
Revises: 20260721_0001
Create Date: 2026-07-21 12:27:55.198025
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "d7bc40428afb"
down_revision: str | None = "20260721_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_prior",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("hour_of_day", sa.Integer(), nullable=False),
        sa.Column("base_score", sa.Float(), nullable=False),
        sa.Column("source_description", sa.String(length=255), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "day_of_week", "hour_of_day", name="uq_activity_prior_slot"
        ),
    )
    op.create_index(
        op.f("ix_activity_prior_platform"), "activity_prior", ["platform"], unique=False
    )
    op.create_table(
        "system_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("setting_key", sa.String(length=100), nullable=False),
        sa.Column("setting_value", sa.Text(), nullable=False),
        sa.Column("is_secret", sa.Boolean(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("setting_key"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("request_path", sa.String(length=500), nullable=True),
        sa.Column("request_method", sa.String(length=20), nullable=True),
        sa.Column("ip_address", sa.String(length=100), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("detail_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["sys_user.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_index(op.f("ix_audit_log_module"), "audit_log", ["module"], unique=False)
    op.create_table(
        "content_article",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("topic", sa.String(length=100), nullable=True),
        sa.Column("target_audience", sa.String(length=150), nullable=True),
        sa.Column("tone", sa.String(length=50), nullable=True),
        sa.Column("keywords_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_content_article_created_by"), "content_article", ["created_by"], unique=False
    )
    op.create_index(op.f("ix_content_article_status"), "content_article", ["status"], unique=False)
    op.create_index(op.f("ix_content_article_title"), "content_article", ["title"], unique=False)
    op.create_table(
        "experiment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("control_description", sa.Text(), nullable=True),
        sa.Column("treatment_description", sa.Text(), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=False),
        sa.Column("conclusion", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "platform_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("account_name", sa.String(length=100), nullable=False),
        sa.Column("publish_mode", sa.String(length=30), nullable=False),
        sa.Column("credential_encrypted", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sys_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_platform_account_user_id"), "platform_account", ["user_id"], unique=False
    )
    op.create_table(
        "account_activity_stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("hour_of_day", sa.Integer(), nullable=False),
        sa.Column("post_count", sa.Integer(), nullable=False),
        sa.Column("avg_impressions", sa.Float(), nullable=False),
        sa.Column("avg_engagement_rate", sa.Float(), nullable=False),
        sa.Column("avg_likes", sa.Float(), nullable=False),
        sa.Column("avg_comments", sa.Float(), nullable=False),
        sa.Column("avg_collects", sa.Float(), nullable=False),
        sa.Column("avg_shares", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "content_variant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("content_text", sa.Text(), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("hashtags_json", sa.JSON(), nullable=False),
        sa.Column("emoji_count", sa.Integer(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=30), nullable=False),
        sa.Column("generation_duration_ms", sa.Integer(), nullable=False),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("manual_edit_ratio", sa.Float(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("original_generated_text", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["content_article.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("article_id", "platform", "version_no", name="uq_variant_version"),
    )
    op.create_index(
        op.f("ix_content_variant_article_id"), "content_variant", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_content_variant_platform"), "content_variant", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_content_variant_review_status"), "content_variant", ["review_status"], unique=False
    )
    op.create_table(
        "generation_task",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("platforms_json", sa.JSON(), nullable=False),
        sa.Column("result_variant_ids_json", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["content_article.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "media_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("source_id", sa.String(length=100), nullable=True),
        sa.Column("image_url", sa.String(length=1000), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=1000), nullable=False),
        sa.Column("photographer_name", sa.String(length=100), nullable=True),
        sa.Column("photographer_url", sa.String(length=500), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("search_keyword", sa.String(length=100), nullable=True),
        sa.Column("usage_type", sa.String(length=30), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["content_article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["content_variant.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_media_asset_article_id"), "media_asset", ["article_id"], unique=False)
    op.create_table(
        "publish_recommendation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("recommended_at", sa.DateTime(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("reason_json", sa.JSON(), nullable=False),
        sa.Column("alternative_times_json", sa.JSON(), nullable=False),
        sa.Column("algorithm_version", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["content_article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["content_variant.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publish_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=False),
        sa.Column("publish_mode", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retry_count", sa.Integer(), nullable=False),
        sa.Column("actual_publish_at", sa.DateTime(), nullable=True),
        sa.Column("published_url", sa.String(length=1000), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=100), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["platform_account.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["article_id"], ["content_article.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["sys_user.id"],
        ),
        sa.ForeignKeyConstraint(["variant_id"], ["content_variant.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_publish_schedule_article_id"), "publish_schedule", ["article_id"], unique=False
    )
    op.create_index(
        op.f("ix_publish_schedule_platform"), "publish_schedule", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_publish_schedule_scheduled_at"), "publish_schedule", ["scheduled_at"], unique=False
    )
    op.create_index(
        op.f("ix_publish_schedule_status"), "publish_schedule", ["status"], unique=False
    )
    op.create_table(
        "engagement_metric",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("metric_date", sa.Date(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("collects", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("followers", sa.Integer(), nullable=False),
        sa.Column("engagement_total", sa.Integer(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=False),
        sa.Column("group_type", sa.String(length=30), nullable=False),
        sa.Column("data_source", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["publish_schedule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "schedule_id", "metric_date", "data_source", name="uq_metric_source_date"
        ),
    )
    op.create_index(
        op.f("ix_engagement_metric_platform"), "engagement_metric", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_engagement_metric_schedule_id"), "engagement_metric", ["schedule_id"], unique=False
    )
    op.create_table(
        "experiment_sample",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=True),
        sa.Column("group_type", sa.String(length=30), nullable=False),
        sa.Column("sample_label", sa.String(length=255), nullable=False),
        sa.Column("metric_value_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiment.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["publish_schedule.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_sample_experiment_id"),
        "experiment_sample",
        ["experiment_id"],
        unique=False,
    )
    op.create_table(
        "publish_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("schedule_id", sa.Integer(), nullable=False),
        sa.Column("step", sa.String(length=50), nullable=False),
        sa.Column("request_summary", sa.Text(), nullable=True),
        sa.Column("response_summary", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["schedule_id"], ["publish_schedule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_publish_log_schedule_id"), "publish_log", ["schedule_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publish_log_schedule_id"), table_name="publish_log")
    op.drop_table("publish_log")
    op.drop_index(op.f("ix_experiment_sample_experiment_id"), table_name="experiment_sample")
    op.drop_table("experiment_sample")
    op.drop_index(op.f("ix_engagement_metric_schedule_id"), table_name="engagement_metric")
    op.drop_index(op.f("ix_engagement_metric_platform"), table_name="engagement_metric")
    op.drop_table("engagement_metric")
    op.drop_index(op.f("ix_publish_schedule_status"), table_name="publish_schedule")
    op.drop_index(op.f("ix_publish_schedule_scheduled_at"), table_name="publish_schedule")
    op.drop_index(op.f("ix_publish_schedule_platform"), table_name="publish_schedule")
    op.drop_index(op.f("ix_publish_schedule_article_id"), table_name="publish_schedule")
    op.drop_table("publish_schedule")
    op.drop_table("publish_recommendation")
    op.drop_index(op.f("ix_media_asset_article_id"), table_name="media_asset")
    op.drop_table("media_asset")
    op.drop_table("generation_task")
    op.drop_index(op.f("ix_content_variant_review_status"), table_name="content_variant")
    op.drop_index(op.f("ix_content_variant_platform"), table_name="content_variant")
    op.drop_index(op.f("ix_content_variant_article_id"), table_name="content_variant")
    op.drop_table("content_variant")
    op.drop_table("account_activity_stat")
    op.drop_index(op.f("ix_platform_account_user_id"), table_name="platform_account")
    op.drop_table("platform_account")
    op.drop_table("experiment")
    op.drop_index(op.f("ix_content_article_title"), table_name="content_article")
    op.drop_index(op.f("ix_content_article_status"), table_name="content_article")
    op.drop_index(op.f("ix_content_article_created_by"), table_name="content_article")
    op.drop_table("content_article")
    op.drop_index(op.f("ix_audit_log_module"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("system_setting")
    op.drop_index(op.f("ix_activity_prior_platform"), table_name="activity_prior")
    op.drop_table("activity_prior")
    # ### end Alembic commands ###
